export default function TermsAndConditions() {
  return (
    <div className="max-w-5xl mx-auto px-4 py-10 text-gray-800">
      <h1 className="text-3xl font-bold mb-6">WorldAutoTrace Terms and Conditions</h1>
      <p className="mb-6">
        Welcome to WorldAutoTrace! These Terms and Conditions govern your use of our website, mobile applications, and services,
        including the purchase and use of vehicle reports. By accessing or using our services, you agree to comply with and be bound
        by these terms. If you do not agree with these terms, please do not use our services.
      </p>

      {/* 1. Definitions */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">1. Definitions</h2>
        <p><strong>"We," "Us," "Our":</strong> Refers to WorldAutoTrace.</p>
        <p><strong>"You," "User":</strong> Refers to any individual or entity using our services.</p>
        <p><strong>"Services":</strong> Includes our website, mobile applications, and vehicle report offerings.</p>
        <p><strong>"Vehicle Report":</strong> A detailed report generated by WorldAutoTrace based on a Vehicle Identification Number (VIN) or other vehicle details.</p>
      </section>

      {/* 2. Use of Services */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">2. Use of Services</h2>
        <p><strong>Eligibility:</strong> You must be at least 18 years old to use our services.</p>
        <p><strong>Account Registration:</strong> You may need to create an account to access certain features. You are responsible for maintaining the confidentiality of your account credentials.</p>
        <p><strong>Accuracy of Information:</strong> You agree to provide accurate and complete information when using our services, including VINs or vehicle details.</p>
      </section>

      {/* 3. Vehicle Reports */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">3. Vehicle Reports</h2>
        <p><strong>Purpose:</strong> Vehicle reports are provided for informational purposes only and should not be the sole basis for making purchasing or financial decisions.</p>
        <p><strong>Accuracy:</strong> While we strive to provide accurate and up-to-date information, we do not guarantee the completeness or accuracy of the reports.</p>
        <p><strong>Ownership:</strong> Vehicle reports are licensed for personal use only. You may not resell, redistribute, or use the reports for commercial purposes without our prior written consent.</p>
      </section>

      {/* 4. Payments and Refunds */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">4. Payments and Refunds</h2>
        <p><strong>Fees:</strong> All fees for vehicle reports are clearly displayed on our website. You agree to pay the specified fees at the time of purchase.</p>
        <p><strong>Refunds:</strong> Refunds are subject to our Refund Policy. Please review the policy for eligibility and procedures.</p>
      </section>

      {/* 5. Prohibited Activities */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">5. Prohibited Activities</h2>
        <p>You agree not to:</p>
        <ul className="list-disc list-inside ml-4">
          <li>Use our services for any illegal or unauthorized purpose.</li>
          <li>Misrepresent your identity or provide false information.</li>
          <li>Attempt to gain unauthorized access to our systems or data.</li>
          <li>Reverse engineer, decompile, or disassemble any part of our services.</li>
        </ul>
      </section>

      {/* 6. Intellectual Property */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">6. Intellectual Property</h2>
        <p><strong>Ownership:</strong> All content, trademarks, logos, and software on our website are the property of WorldAutoTrace or its licensors.</p>
        <p><strong>License:</strong> We grant you a limited, non-exclusive, non-transferable license to use our services for personal, non-commercial purposes.</p>
      </section>

      {/* 7. Limitation of Liability */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">7. Limitation of Liability</h2>
        <p><strong>Disclaimer:</strong> Our services are provided "as is" and "as available." We do not guarantee that the services will be error-free, uninterrupted, or meet your expectations.</p>
        <p><strong>Limitation:</strong> To the fullest extent permitted by law, WorldAutoTrace shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of our services.</p>
      </section>

      {/* 8. Indemnification */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">8. Indemnification</h2>
        <p>
          You agree to indemnify and hold WorldAutoTrace harmless from any claims, damages, losses, or expenses (including legal fees) arising from your use of our services or violation of these terms.
        </p>
      </section>

      {/* 9. Termination */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">9. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to our services at any time, without notice, for any reason, including violation of these terms.
        </p>
      </section>

      {/* 10. Changes to Terms and Conditions */}
      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">10. Changes to Terms and Conditions</h2>
        <p>
          We may update these Terms and Conditions from time to time. Any changes will be posted on this page with an updated effective date. Your continued use of our services constitutes acceptance of the revised terms.
        </p>
      </section>
    </div>
  );
}